name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: JanoAngulo
          UTC_OFFSET: 8
          BRANCH_NAME: profile-summary-card-output
